version: "3.6"

services:
  frontend:
    build:
      dockerfile: ../dockerfiles/dev/frontend
      context: ./web-client
      args:
        NODE_VERSION: $NODE_VERSION
    volumes:
      - "./web-client:/scores/web-client"
    environment:
      - BACKEND_URL=http://backend:8080

  backend:
    build:
      dockerfile: ../dockerfiles/dev/backend
      context: ./backend
      args:
        version: $VERSION
        GO_VERSION: $GO_VERSION
    volumes:
      - "./data/backend:/srv/scores"
    command:
      - "-mode"
      - "debug"
      - "-connection"
      - "postgres://postgres:test@db?sslmode=disable"
      - "-provider"
      - "postgres"
      - "-gauth"
      - "/srv/scores/client_secret.json"
    security_opt:
      - seccomp:unconfined
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:40000:40000"

  envoy:
    image: envoyproxy/envoy:$ENVOY_VERSION
    volumes:
      - "./certs:/usr/share/letsencrypt/scores.network"
      - "./conf/envoy.prod.test.yaml:/etc/envoy/envoy.yaml"
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8001:8001"

  db:
    image: "postgres:$POSTGRES_VERSION"
    ports:
      - "127.0.0.1:5432:5432"

  pgadmin:
    image: dpage/pgadmin4:$PGADMIN_VERSION
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.at
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - "127.0.0.1:81:80"
