version: "3.6"

services:
  envoy:
    image: envoyproxy/envoy:${ENVOY_VERSION}
    network_mode: "host"
    volumes:
      - "./certs:/usr/share/letsencrypt/scores.network"
      - "./conf/envoy.yaml:/etc/envoy/envoy.yaml"
    ports:
      - "80:80"
      - "443:443"
      - "7000:7000"
      - "127.0.0.1:8001:8001"

  db:
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "127.0.0.1:5432:5432"

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.at
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - "127.0.0.1:81:80"
